Resources:
  MySnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: MySnsTopic
      Subscription:
        - Endpoint: ${self:custom.app_config.EMAIL}
          Protocol: email
      TopicName: MySnsTopic
