service: send-sns-from-lambda
custom:
  app_config: ${file(./config.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'SNS:Publish'
      Resource:
        Ref: MySnsTopic

resources:
  - ${file(./resources.yml)}

functions:
  hello:
    handler: handler.hello
    environment:
      TOPIC_ARN:
        Ref: MySnsTopic
